# Model arguments
model_name_or_path: /shared/public/models/Mistral-7B-v0.1
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
dataset_mixer:
  /shared/public/data/jaszhu/ultrafeedback-binarized-preferences-cleaned: 1.0
dataset_splits:
- train
preprocessing_num_workers: 128

# ORPOTrainer arguments
bf16: true
beta: 0.05
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id: mistral-7b-orpo-beta
learning_rate: 5.0e-6
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1792
num_train_epochs: 3 
optim: adamw_torch
output_dir: /shared/public/models/quantized_model/alignment_handbook_models/mistral-7b-orpo-beta10
per_device_train_batch_size: 8
push_to_hub: false
report_to:
- tensorboard
save_strategy: "epoch"
seed: 42
hub_private_repo: false